Bundle 'gmarik/vundle'
Bundle 'bling/vim-airline'
Bundle 'ctrlp.vim'
Bundle 'EasyMotion'
Bundle 'surround.vim'
Bundle 'https://github.com/jelera/vim-javascript-syntax'
Bundle 'https://github.com/tpope/vim-unimpaired'
Bundle 'https://github.com/scrooloose/syntastic'
Bundle 'https://github.com/scrooloose/nerdtree'
Bundle 'https://github.com/tmhedberg/matchit'
Bundle 'https://github.com/vim-scripts/hexHighlight.vim'
Bundle 'https://github.com/milkypostman/vim-togglelist'
Bundle 'https://github.com/SirVer/ultisnips'
Bundle 'https://github.com/tpope/vim-abolish'
Bundle 'https://github.com/othree/html5.vim/'
Bundle 'https://github.com/marijnh/tern_for_vim'
if has('win16') || has('win95') || has('win32') || has('win64')
else
Bundle 'https://github.com/Valloric/YouCompleteMe'
endif
